 services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
   #ports:
   # - '3000:3000'
    network_mode: "host"
    environment:
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
     - GF_PLUGINS_PREINSTALL=yesoreyeram-infinity-datasource     
    volumes:
     - 'grafana_storage:/var/lib/grafana'
 volumes:
  grafana_storage: {}
